# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
[tool.black]
target-version = ["py311"]
line-length = 88


# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
profile = "black"
py_version = "auto"
skip_gitignore = true
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


# https://docs.pytest.org/en/latest/reference/customize.html#pyproject-toml
[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = [
    "tests",
]
env = []


# https://coverage.readthedocs.io/en/latest/config.html
[tool.coverage.run]
branch = true
command_line = "-m pytest"
omit = [
    ".venv/*",
    "venv/*",
    "tests/*",
]


[tool.coverage.report]
precision = 2
show_missing = true
exclude_lines = [
    "pragma: no cover",
]


# flake8 is not here. See: https://github.com/PyCQA/flake8/issues/234
