# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Code Linting"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pipenv"
          cache-dependency-path: "Pipfile.lock"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv sync --system --dev

      - name: flake8 check
        run: flake8 .

      - name: black check
        run: black --check .

      - name: isort check
        run: isort --check .
