# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Unit Testing"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage-pytest:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pipenv"
          cache-dependency-path: "Pipfile.lock"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv sync --system --dev

      - name: Run Tests
        run: coverage run
